filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'src/PTS/Routing/Middlewares/*'

checks:
    php:
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true

coding_style:
    php: {  }

tools:
    external_code_coverage: true

build:
    environment:
        php:
            version: 7.0

    tests:
        override:
            -
                command: 'phpunit  --configuration ./test/phpunit.xml --coverage-clover=test/clover.xml'
                coverage:
                    file: 'test/clover.xml'
                    format: 'php-clover'
